### ISSUE TITLE
What does it mean "TODO: wait for protobuf to be fixed" in v2 folder?

### ISSUE THREAD

**Issue by filipemtz** [cmpute/xviz.py#2]
Dear @cmpute , I am considering implementing a C++ version/binding of xviz protocol for using along with the avs.auto web-based GUI. Your code is quite simple, straightfoward and well-organized, hence my plan is to use it as a guide. Do you think this is a good idea? 

The README from v2 folder contains the comment that I mention in the title. I was wondering what has to be fixed in the protobuf. Is there a problem in the proto files from xviz repository? Which problems are these? 

Be safe and thanks for your code.

**Comment by cmpute** [comment]
At the point where I coded this, the protobuf definitions in the xviz master branch are not able to be compiled due to some errors. I think right now they may have fixed but I didn't check it again. You can regenerate the protobuf as you like.

BTW, If you want a C++ implementation, there's one implemented recently https://github.com/uber/xviz/pull/592

**Comment by filipemtz** [comment]
Thanks for clarifying the message and super thanks for indicating the cpp implementation!!

**Comment by cmpute** [comment]
You're welcome :)
